eventvisualizer/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.search_events, name='search_events'),
    url(r'NewEvents/$', views.new_events, name='new_events'),
    url(r'NewEvents/SaveEvent/$', views.save_event, name='save_events'),
    url(r'About/$', views.about, name='about'), 
]

idp/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^', include('eventvisualizer.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', admin.site.urls),
]

eventvisualizer/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

eventvisualizer/forms.py
# -*- encoding: utf-8-*-
from django import forms
#from leaflet.forms.widgets import LeafletWidget
from datetime import date, timedelta, datetime
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class FullUserCreationForm(UserCreationForm):
    """
    """
 
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['email', 'username', 'first_name', 'last_name', "password1", "password2" ]
        #fields = ("username", "email", )

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

class EventSearchForm(forms.Form):
    """
    """
 
    event_name = forms.CharField(label='Search query', max_length=100, initial="M")
    start_date = forms.DateField(initial=datetime.now() - timedelta(7))
    end_date = forms.DateField(initial=datetime.now())
    social_media = forms.CharField(widget = forms.HiddenInput(), required = False)
    minLat = forms.FloatField( widget = forms.HiddenInput(), required = True)
    maxLat = forms.FloatField( widget = forms.HiddenInput(), required = True)
    minLon = forms.FloatField(widget = forms.HiddenInput(), required = True)
    maxLon = forms.FloatField( widget = forms.HiddenInput(), required = True)

class EventSaveForm(forms.Form):
    """
    """
 
    ev_name = forms.CharField(label='Name', max_length=100)
    #ev_category = forms.ChoiceField(label='Category', choices=CATEGORIES)
    ev_category = forms.ChoiceField(label='Category', widget=forms.Select(attrs={"onChange":'dropdown_handler(this.value)'}) )
    ev_subcategory = forms.ChoiceField(label='Subcategory')
    

eventvisualizer/views.py
# -*- encoding: utf-8-*-
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.shortcuts import redirect
from django.http import HttpResponse
from django.http import JsonResponse
from django.template import loader
from django.template import RequestContext

from django.http import HttpResponseRedirect

from .forms import EventSearchForm
from .forms import EventSaveForm
from datetime import date, timedelta, datetime
import json

from inc.helper import GeoBoundingBox

from Framework.EventDetection.TwitterEventDetection import TwitterEventDetection
from Framework.EventDetection.FlickrEventDetection import FlickrEventDetection
from Framework.EventDetection.InstagramEventDetection import InstagramEventDetection
from Framework.EventDetection.FacebookEventDetection import FacebookEventDetection

from Framework.EventProvider.DatabaseEventProvider import DatabaseEventProvider
from Framework.EventProvider.FacebookEventProvider import FacebookEventProvider
from Framework.EventProvider.XingEventProvider import XingEventProvider

date_format = ""

class EventEncoder(json.JSONEncoder):
    """
    JSONEncoder subclass that leverages an object's `__json__()` method,
    if available, to obtain its default JSON representation.

    """
    def default(self, obj):
        if hasattr(obj, '__json__'):
            return obj.__json__()
        return json.JSONEncoder.default(self, obj)
       

def index(request):
    """
    """
    template = loader.get_template('eventvisualizer/base.html')
    return HttpResponse(template.render(request))

def about(request):
    template = loader.get_template('eventvisualizer/about.html')
    return HttpResponse(template.render(request))

# search for events in the database
def search_events(request):
    """
    """

    if request.method == 'GET':
        formData = getFormData(request)
        if formData["social_media"] == "Database":
            inputValidation = checkDatabaseSearchInput( formData["event_name"], formData["start_date"],formData["end_date"],formData["category"])

            if inputValidation["error"] == 1:
                return JsonResponse(inputValidation)

            return showDatabaseEvents(request)
        
        if "eventid" in formData:
            return showDatabaseEvent(formData, request)

    form = EventSearchForm()
    template = loader.get_template('eventvisualizer/search_events.html')
    return HttpResponse(template.render({'form' : form}, request))


# store current event in database
def save_event(request):
    """
    """
 
    if not request.user.is_authenticated:
        context = {
            "error" : 1,
            "message" : "Please login first!"
         }
        return JsonResponse(context)

    if request.method == 'POST':
        requestData = request.POST        
        dbCon = DatabaseEventProvider()
        result = dbCon.storeEventToDatabase(requestData)
        return JsonResponse(result)

    form = EventSearchForm()
    save_event_form = EventSaveForm()
    template = loader.get_template('eventvisualizer/new_events.html')
    return HttpResponse(template.render({'form' : form, 'save_event_form' : save_event_form}, request))

# search for new events with the framework
def new_events(request):
    """
    """

    if request.method == 'GET':
        formData = getFormData(request)

        if 'source' in formData:
            form = EventSearchForm()
            form.event_name = formData["name"]
            form.start_date = formData["startdate"]
            form.end_date = formData["enddate"]
            save_event_form = EventSaveForm()
            template = loader.get_template('eventvisualizer/new_events.html')
            return HttpResponse(template.render({'form' : form, 'save_event_form' : save_event_form, 'name' : formData["name"], 'startdate' : formData["startdate"], 'enddate' : formData['enddate']}, request))
            

        if formData['social_media'] != "":
            validInput = checkSocialMediaSearchInput(formData['start_date'], formData['end_date'])

            if validInput["error"] == 1:
                return JsonResponse(validInput)

            if formData['social_media'] == 'Twitter':
                return showTwitterEvents(request)
            elif formData['social_media'] == 'Flickr':
                return showFlickrEvents(request)
            elif formData['social_media'] == 'Instagram':
                return showInstagramEvents(request)
            elif formData['social_media'] == 'Facebook':
                return showFacebookEvents(request)
            elif formData['social_media'] == 'Xing':
                return showXingEvents(request)
    
    form = EventSearchForm()
    save_event_form = EventSaveForm()
    template = loader.get_template('eventvisualizer/new_events.html')
    return HttpResponse(template.render({'form' : form, 'save_event_form' : save_event_form}, request))

def showDatabaseEvent(formData, request):
    """
    """

    form = EventSearchForm()
    template = loader.get_template('eventvisualizer/search_events.html')
    dbCon = DatabaseEventProvider()
    event = dbCon.getEvent(formData["eventid"])
    event = sortEventsByLocation(event)
    json_event = json.dumps(event, cls=EventEncoder)
    context = {
        "content": json_event,
        "social_media" : "Database",
        "form" : formData['form']
    }
    return HttpResponse(template.render(context, request))

# show database events
def showDatabaseEvents(request):
    """
    """
 
    formData = getFormData(request)
    dbCon = DatabaseEventProvider()
    events = dbCon.getEvents(formData['event_name'],formData['start_date'], formData['end_date'],formData['category'], formData['geoBoundingBox'])
    events = sortEventsByLocation(events)
    json_events = json.dumps(events, cls=EventEncoder)
    context = {
        "content": json_events,
        "social_media" : "Database"
    }
    return JsonResponse(context)

# show events from twitter
def showTwitterEvents(request):
    """
    """
 
    formData = getFormData(request)
    twitterED = TwitterEventDetection(formData['event_name'],  formData['start_date'], formData['end_date'], formData['geoBoundingBox'])
    return showEvents(request,twitterED, formData['form'], "Twitter")

#show events from flickr
def showFlickrEvents(request):
    """
    """
 
    formData = getFormData(request)
    flickrED = FlickrEventDetection(formData['start_date'], formData['end_date'], formData['geoBoundingBox'])
    return showEvents(request, flickrED, formData['form'], "Flickr")

# show events from instagram
def showInstagramEvents(request):
    """
    """

    formData = getFormData(request)
    instagramED = InstagramEventDetection(formData['start_date'], formData['end_date'], formData['geoBoundingBox'])
    return showEvents(request, instagramED, formData['form'], "Instagram")

# show events from facebook
def showFacebookEvents(request):
    """
    """
 
    formData = getFormData(request)
    fbProvider = FacebookEventProvider()
    events = fbProvider.getEvents(formData['event_name'],formData['start_date'], formData['end_date'], formData['geoBoundingBox'])
    return sendEvents(request, events, formData['form'], "Facebook")

    # show events from facebook
def showXingEvents(request):
    """
    """
 
    formData = getFormData(request)
    xingProvider = XingEventProvider()
    events = xingProvider.getEvents(formData['event_name'],formData['start_date'], formData['end_date'], formData['geoBoundingBox'])
    return sendEvents(request, events, formData['form'], "Xing")

# show the detected events
def showEvents(request, eventDetection, form, social_media):
    """
    """
 
    events = eventDetection.getContent()
    return sendEvents(request, events, form, social_media)


def sendEvents(request, events, form, social_media):
    """
    """
 
    events = sortEventsByLocation(events)
    json_events = json.dumps(events, cls=EventEncoder)
    template = loader.get_template('eventvisualizer/new_events.html')
    save_event_form = EventSaveForm()
    context = {
        "content": json_events,
        "social_media" : social_media,
    }
    return JsonResponse(context)

# get the form data from django input forms
def getFormData(request):
    """
    """
 
    data = { 'event_name':"", 'start_date':"", 'end_date' : "", 'form' : EventSearchForm(), 'social_media' : ""} #, "minLat" : "", "minLon" : "", "maxLat" : "", "maxLon" : ""}
    
    if request.method == 'GET':
        # create a form instance and populate it with data from the request:
        requestDict = request.GET.dict()
        if 'Query' in requestDict:
            if 'SocialMedia' in requestDict:
                if 'MinLat' in requestDict:
                    minLat = float(requestDict['MinLat'])
                    minLon = float(requestDict['MinLon'])
                    maxLat = float(requestDict['MaxLat'])
                    maxLon = float(requestDict['MaxLon'])

                    data['event_name'] = requestDict['Query']
                    data['start_date'] = requestDict['StartDate']
                    data['end_date'] = requestDict['EndDate']
                    data['social_media'] = requestDict['SocialMedia']
                    data['geoBoundingBox'] = GeoBoundingBox(minLat, minLon, maxLat, maxLon )
                    social_media = requestDict['SocialMedia']
                    if data['social_media'] != "Database":

                        start_date = None
                        end_date = None
                        if data['start_date'] == "":
                            if data['end_date'] == "":
                                end_date = datetime.now().date()
                                start_date = (datetime.now() - timedelta(days = 14)).date()
                                data['start_date'] = start_date
                                data['end_date'] = end_date

                            else:

eventvisualizer/templates/eventvisualizer/about.html
{% extends 'account/base.html' %} 
{% block initialize %}

{% block about_active %} class="active" {% endblock %}

{% block content %}

<p style="align:center; margin:20px;">

<h3 style="align:center; margin:20px;">About us</h3>
    <p style="align:center; margin:20px;">This application was developed by three students during a project at the Chair of Cartography, TU Munich.
    <br>
    <br>
The website consists of two main parts. The first part displays events which have been saved from different sources on OpenStreetMap. The other part of the application consists of detecting events from social media. This means that we use the API of Facebook, Twitter, Flickr and Xing to detect events which can be saved to an OpenStreetMap server. Saving this event gives other users the opportunity to find this event and may participate or they can see what happened in the past. 
<br>
<br>
This tool extracts meaningful volunteered geographic information (VGI) about any kind of events from different social media platforms and analyse the collected data. After analyzing the data, clusters can be found and these clusters are handled as event. 
The area of this application is currently restricted to Munich in Germany and its surrounding areas. 
<br>
<br>
For feedback or questions please contact us 
<a>openeventmaptum@gmail.com</a>
 </p>

 </p>
{% endblock %}

{% endblock %}

eventvisualizer/templates/eventvisualizer/base_map.html
 {% extends 'eventvisualizer/navbar.html' %}
  {% block head %}
 {% load staticfiles %} 
  {% load leaflet_tags %} 
  {% leaflet_js plugins="ALL" %} 
  {% leaflet_css plugins="ALL" %}
<html>

<head>
    <meta charset="UTF-8">

    <title>Social Media Event Map</title>

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <!-- BOOTSTRAP -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{%static 'eventvisualizer/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{%static 'eventvisualizer/bootstrap/css/bootstrap-theme.min.css' %}">
    <script type="text/javascript" src="{% static 'eventvisualizer/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Bootstrap Date-Picker Plugin -->
    <script type="text/javascript" src="{% static 'eventvisualizer/datepicker/bootstrap-datepicker.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'eventvisualizer/datepicker/bootstrap-datepicker3.css' %}" />
    <script type="text/javascript" src="{% static 'eventvisualizer/datepicker/datepicker.js' %}"></script>

    <link rel="stylesheet" href="{% static 'eventvisualizer/font-awesome/css/font-awesome.min.css' %}" />


    <!-- TWITTER ZEUG -->
    <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>

    <!-- MAP STUFF -->
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />

    <link rel="stylesheet" href="{%static 'eventvisualizer/leaflet/css/MarkerCluster.css' %}">
    <link rel="stylesheet" href="{%static 'eventvisualizer/leaflet/css/MarkerCluster.Default.css' %}">
    <script type="text/javascript" src="{% static 'eventvisualizer/leaflet/js/leaflet.markercluster.js' %}"></script>

    <script type="text/javascript" src="{% static 'eventvisualizer/leaflet/js/leaflet-legend.js' %}"></script>
    <link rel="stylesheet" href="{%static 'eventvisualizer/leaflet/css/leaflet-legend.css' %}">

    <link rel="stylesheet" href="{%static 'eventvisualizer/leaflet/css/leaflet.awesome-markers.css' %}">
    <script type="text/javascript" src="{% static 'eventvisualizer/leaflet/js/leaflet.awesome-markers.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'eventvisualizer/leaflet/js/leaflet-heat.js' %}"></script>

    <script type="text/javascript" src="{% static 'eventvisualizer/helper.js' %}"></script>
    <script type="text/javascript" src="{% static 'eventvisualizer/token.js' %}"></script>
    <script type="text/javascript" src="{% static 'eventvisualizer/document.js' %}"></script>
    <script type="text/javascript" src="{% static 'eventvisualizer/categories.js' %}"></script>
    <script type="text/javascript" src="{% static 'eventvisualizer/map.js' %}"></script>
    <script type="text/javascript" src="{% static 'eventvisualizer/search_buttons.js' %}"></script>

    <link rel="stylesheet" href="{%static 'eventvisualizer/css/main.css' %}"> {% block initialize %} {% endblock %}

</head>
<div id="grayBackground">
{% endblock %} {% block nav_body %}

<body>
    <div class="container-fluid">
        <div class="row row-full">
            <!--LEFT PANE-->
            <div class="col-sm-4">
                <div class="leftside">
                    {% block left_content %} {% endblock %}
                    <div id="" style="overflow-y: scroll; height:500px;">
                        <ul id="Additional_Info">
                        </ul>
                    </div>
                </div>
            </div>

            <!--RIGHT PANE-->
            <div class="col-sm-8">
                <div id="legend_place"></div>
                <div id="map">
                    {% leaflet_map "main" callback="window.initialize" %}
                </div>
            </div>
        </div>
    </div>
	
</body>


</div>

<div id="loadingDiv"></div>
</html>

{% endblock %}

eventvisualizer/templates/eventvisualizer/navbar.html
{% load staticfiles %}
 {% block head %}
 {% endblock %}

<div id="menu" class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" style="padding-top: 15px; padding-left: 10px;margin-right: 30px;" href="#">SocialMediaEventMap</a>
    </div>
    <ul class="nav navbar-nav">
      <li {% block database_active %}{% endblock %}> <a href='{% url "search_events" %}' data-value=""><i class="fa fa-search" aria-hidden="true"></i> SEARCH EVENTS</a></li>
      <li{% block new_events_active %}{% endblock %}><a href='{% url "new_events" %}' data-value=""><i class="fa fa-clock-o" aria-hidden="true"></i> REAL-TIME EVENTS</a></li>
        <li {% block about_active %}{% endblock %}><a href='{% url "about" %}' data-value=""><i class="fa fa-book" aria-hidden="true"></i> ABOUT</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if not user.is_authenticated %}
      <li {% block signin_active %}{% endblock %}><a href='/edsm/accounts/signup'><span class="fa fa-user"></span> Sign Up</a></li>
      <li {% block login_active %}{% endblock %}><a href='/edsm/accounts/login'><span class="fa fa-sign-in"></span> Login</a></li>
      {% endif %} {% if user.is_authenticated %}
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="fa fa-user"></span> {{ user.get_username }}
        <span class="caret"></span></a>
        <ul class="dropdown-menu" style="z-index: 999;">
          <li {% block pw_change_active %}{% endblock %}><a href='/edsm/accounts/password/change' data-value="pw_change">CHANGE PASSWORD</a></li>
          <li {% block logout_active %}{% endblock %}><a href='/edsm/accounts/logout' data-value="logout">LOGOUT</a></li>
        </ul>
      </li>
      {% endif %}
    </ul>
  </div>
</div>


{% block nav_body %}{% endblock %}

eventvisualizer/templates/eventvisualizer/new_events.html
{% extends 'eventvisualizer/base_map.html' %} 

{% block initialize %}
    <script type="text/javascript">
		function initialize(map, options) {
			//createLegend();
			setDjangoInput("{{content}}", "{{query}}", "{{social_media}}", "New_Events");
			setInitialValueForNewEvents("{{name}}", "{{startdate}}", "{{enddate}}");
			map_init(map,options);
		}
	</script>
{% endblock %}


{% block new_events_active %}
	class="active"
{% endblock %}

{% block left_content %}
<form action="" method="POST">
	{% csrf_token %}

	<h4>Real-Time Event Search</h4>
	<!--SEARCH-->
	<div class="row">
		<div class="col-md-12">
			<div class="input-group search-input">
				<span class="input-group-addon"><i class="fa fa-search" aria-hidden="true"></i></span>
				<input class="form-control" id="id_event_name" value="" maxlength="100" name="event_name" type="text" required placeholder="Input keywords for event search">
			</div>
						<div class="input-group search-input">
							<span class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></span>
							<input type="text" class="form-control" id="id_start_date" value="" name="date" placeholder="Startdate (DD/MM/YYYY)">
						</div>
						<div class="input-group search-input">
							<span class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></span>
							<input type="text" class="form-control" id="id_end_date" value="" name="date" placeholder="Enddate (DD/MM/YYYY)"><br>
						</div>
		</div>
	</div>
	<!--SOCIAL MEDIA SEARCH BUTTONS-->
	<div class="row top-buffer">
		<div class="btn-group btn-group-round btn-block pad search-input">
			<button id="search_facebook" type="button" name="SubmitBtn" onclick="searchFacebook()" class="btn sm"><i class="fa fa-facebook-official"></i> Facebook</button>
			<button id="search_twitter" type="button" name="SubmitBtn" onclick="searchTwitter()" class="btn sm"><i class="fa fa-twitter"></i> Twitter</button>
			<button id="search_flickr" type="button" name="SubmitBtn" onclick="searchFlickr()" class="btn sm"><i class="fa fa-flickr"></i> Flickr</button>
			<button id="search_xing" type="button" name="SubmitBtn" onclick="searchXing()" class="btn sm"><i class="fa fa-xing"></i> XING</button>
			<button id="clear_form" type="button" name="SubmitBtn" onclick="clearForm()" class="btn sm"><i class="fa fa-trash"></i> CLEAR</button>
		</div>
		<input class="btn save" type="button" data-toggle="modal" data-target="#saveEvent" id="show_save_form" value="Save Event" />
	</div>
<div id="loading">
	Loading events from social media...
	<i class="fa fa-spinner fa-pulse fa-fw fa-2x"></i>
</div>


<!--MODAL DIALOGUE FOR SAVING EVENTS-->
{% if user.is_authenticated %}
  <div class="modal fade" id="saveEvent" role="dialog">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Save Event</h4>
        </div>
        <div class="modal-body">
			<h6> Event Name: </h6>	
			<input class="form-control" id="id_ev_name"> 
			<h6> Comment: </h6>	
			<input class="form-control" id="id_ev_comment"> 
			 <h6 class="top-buffer">Category: </h6>
			<select class="form-control" id="id_ev_category" onchange="setSubcategoriesForCurrentValue()"></select>
			 <h6 class="top-buffer">Subcategory: </h6>
			<select class="form-control" id="id_ev_subcategory"></select>
			 <h6 class="top-buffer">Howoften: </h6>
			<select class="form-control" id="id_ev_howoften"></select>
        </div>
        <div class="modal-footer">
		<input id="save_event" class="btn btn-default" data-dismiss="modal" value="Save">	
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  {% else %}
   <div class="modal fade" id="saveEvent" role="dialog">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Login required</h4>
        </div>
        <div class="modal-body">
	 <div class="alert alert-warning">
   	  <strong>Warning!</strong> You must be logged in to save an event to the database.
        </div>
			 Please login or sign up to continue.
		<br> <a href='/edsm/accounts/login' class="btn btn-info" data-value="about" role="button">LOGIN</a>
		 <a href='/edsm/accounts/signup' class="btn btn-info" data-value="about" role="button">SIGN UP</a>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>

{% endif %}

{% endblock %}

eventvisualizer/templates/eventvisualizer/search_events.html
{% extends 'eventvisualizer/base_map.html' %} {% block initialize %}
<script type="text/javascript">
		function initialize(map, options) {
			//generateLegend();
			setDjangoInput("{{content}}", "{{query}}", "{{social_media}}", "Database_Events");
			map_init(map,options);
		}
	</script> {% endblock %} 
	{% block database_active %} class="active" {% endblock %}
	 {% block left_content %}
<form>
	{% csrf_token %}

	<h4>Search for Events</h4>
	<!--SEARCH-->
	<div class="row">
		<div class="col-md-12">
			<div class="input-group search-input">
				<span class="input-group-addon"><i class="fa fa-search" aria-hidden="true"></i></span>
				<input class="form-control" id="id_event_name" value="" maxlength="100" name="event_name" type="text" required placeholder="Input keywords for event search">
			</div>
			<div class="input-group search-input">
				<span class="input-group-addon"><i class="fa fa-tags" aria-hidden="true"></i></span>
				<!--<input class="form-control" id="id_category" value="" maxlength="100" name="event_name" type="text" required placeholder="Category"> -->
				<select class="form-control" id="id_category" ></select>
			</div>
			<div class="input-group search-input">
				<span class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></span>
				<input type="text" class="form-control" id="id_start_date" value="" name="date" placeholder="Startdate (DD/MM/YYYY)">
			</div>
			<div class="input-group search-input">
				<span class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></span>
				<input type="text" class="form-control" id="id_end_date" value="" name="date" placeholder="Enddate (DD/MM/YYYY)"><br>
			</div>
		</div>
	</div>

	<!--DATEPICKER-->
	<div class="bootstrap-iso">
		<div class="row top-buffer search-input">
			<div class="row pad inline-block">
				<div class="top-buffer col-md-12">
					<button type="button" id="search_database" onclick="searchSocialMedia('Database')" class="btn sm edsm"><i class="fa fa-search" aria-hidden="true"></i> Search</button>
					<button type="reset" class="btn sm edsm"><i class="fa fa-trash"></i> Reset</button>
					<!--<button id="search_database" name="SubmitBtn" class="btn"><i class="fa fa-search" aria-hidden="true"></i> Search</button>-->
					<!--<input id="search_database" class="btn" value="Search" name="SubmitBtn">
				<button type="reset" class="btn"> Clear</button>-->
				</div>
			</div>
		</div>
	</div>
</form>

<div id="loading">
	Loading events from database...
	<i class="fa fa-spinner fa-pulse fa-fw fa-2x"></i>
</div>

{% endblock %}